### ISSUE TITLE
Commas in results

### ISSUE THREAD

**Issue by melriksdesign** [jvasallo/jquery-mortgage#2]
This is an awesome script.  Something to kick around, we needed the output to have USA-style commas added.  toLocaleString() isn't cross-browser, but I found a similar function on Stack Overflow

Credit to Paul S for the conversion function.
http://stackoverflow.com/questions/16157762/tolocalestring-not-supported-in-all-browsers

`	
function localeString(x, sep, grp) {
    var sx = (''+x).split('.'), s = '', i, j;
    sep || (sep = ','); // default seperator
    grp || grp === 0 || (grp = 3); // default grouping
    i = sx[0].length;
    while (i > grp) {
        j = i - grp;
        s = sep + sx[0].slice(j, i) + s;
        i = j;
    }
    s = sx[0].slice(0, i) + s;
    sx[0] = s;
    return sx.join('.')
}
`

and then updated the output lines like this

`<td>$" + (localeString(parseFloat(loan_amount))) + "</td>`

or

`<td><strong>$" + (localeString(parseFloat(total_mortgage).toFixed(2))) + "</strong></td>`

**Comment by jvasallo** [comment]
Nice issue, I am not going to lie this code is probably not as optimized nor tested as it could be. Reviewing the issue now and determining best implementation!

**Comment by jvasallo** [comment]
@melriksdesign I have updated to support this in the code, this code is quite messy since I did this a few years ago, if you want to patch it up/optimize it a Pull Request is always welcome! :)

Check the changes here:
https://github.com/jvasallo/jquery-mortgage/commit/c449f626b7e98f0d329047906deb1614d11f5176

By default, it will use commas as the separator, but feel free to change it if needed.
